### ISSUE TITLE
How to assess the MySQL servers command line?

### ISSUE THREAD

**Issue by ghost** [numtel/meteor-mysql-server#2]
How can I assess the MySQL command-line? Like I would with the meteor mongo command. also would there be any problems with using both MySQL and mongo? thanks

**Comment by numtel** [comment]
You would need to install the MySQL command line client separately. There should be no problem running both MySQL and Mongo as they use different ports.

**Comment by ghost** [comment]
ok thanks

**Comment by numtel** [comment]
That's a good idea to be able to be able to use it like `meteor mongo`... I may try to figure out how to do that. :+1:
