### ISSUE TITLE
Error: Cannot find module on startup

### ISSUE THREAD

**Issue by Abbraxar** [numtel/meteor-mysql-server#6]
Hello,
i've got an issue on meteor startup after running in my repository
meteor add numtel:mysql-server

Here the log :
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
=> Modified -- restarting.
=> Errors prevented startup:                  

   While loading plugin `mysqlServer` from package
   `numtel:mysql-server`:
   module.js:338:15: Cannot find module
   '/root/.meteor/packages/meteor-tool/.1.1.9.1skzmvo++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/fiber-helpers.js'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object._.extend.Npm.require
   (/tools/isobuild/bundler.js:1276:22)
   at Package (packages/mysqlServer/plugin/mysqlServer.js:23:1)
   at <runJavaScript-69>:216:4
   at <runJavaScript-69>:223:3

I'm pretty new to node, npm and meteor world so I hope it's not an obvious mistake from me.
Thanks

**Comment by numtel** [comment]
Nope not an obvious mistake on your part. The Meteor build system changed with the new version 1.2 and it broke this package. Try the just released version 1.0.1 of this package for the fix.

**Comment by Abbraxar** [comment]
Ah great !
It works perfectly, thank you.
